
import { Raleway } from "next/font/google";
import Header from "./components/Header";
import { CtxLoginProvider } from "./context/CtxLogin";


import "./globals.css";

const raleway = Raleway({  weight: ["400", "700"],  subsets: ["latin"],});

export const metadata = {
  title: "KratiAnalitik",
  description: "Generated by j4Data",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={raleway.className}>
        <CtxLoginProvider>
          <Header />
          {children}
        </CtxLoginProvider>
      </body>
    </html>
  );
}
